p8105\_hw6\_mrc2229
================
Matthew Curran
November 19, 2019

Problem 1
=========

Bring in and clean the birthweight data consisting of roughly 4000 children.
----------------------------------------------------------------------------

``` r
birthweight_data = read_csv ("./data/birthweight.csv") %>%
  janitor::clean_names() %>%
  rename(
    b_sex=babysex,
    b_headcirc=bhead,
    b_length=blength,
    b_bwt=bwt,
    m_wt_delivery=delwt, 
    fam_income_month=fincome, 
    f_race=frace,
    gest_age_wks=gaweeks, 
    m_age_menarche=menarche, 
    m_hgt=mheight,
    m_age_delivery=momage,
    m_race=mrace,
    births_prior=parity,
    prev_low_bwt=pnumlbw,
    prev_small_gest=pnumsga,
    m_prepreg_bmi=ppbmi,
    m_prepreg_wt=ppwt,
    ave_smoke=smoken,
    m_preg_wt_gain=wtgain
  ) %>%
  mutate(f_race=as.factor(f_race), m_race=as.factor(m_race), b_sex=as.factor(b_sex), malform=as.factor(malform)) 
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_double()
    ## )

    ## See spec(...) for full column specifications.

-   Variables were renamed to be more descriptive and follow a more consistent structure.
-   Variables for race, sex, and presence of malformations that could affect weight were converted from numeric to factor variables.
-   There was no missing data to fill in or remove.
-   There are 4342 observations in the birthweight data set and 20 variables.

My Predictive Model
-------------------

-   I hypothesize that a mother’s weight gain during pregnancy (in pounds), gestational age (in weeks), and the mother's age during delivery are significant predictors for predicting a baby's birthweight.
-   Univariate anaylsis was run on all three of these predictors first to see their individual significance before adding them to a multivariable model, with a 5% level of significance. Only individually significant variables are added to the final model.

``` r
wt_gain_model = lm(b_bwt ~ m_preg_wt_gain, data = birthweight_data)
summary(wt_gain_model)
```

    ## 
    ## Call:
    ## lm(formula = b_bwt ~ m_preg_wt_gain, data = birthweight_data)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -2421.89  -297.59    20.12   324.14  1619.69 
    ## 
    ## Coefficients:
    ##                 Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)    2858.9138    16.9621  168.55   <2e-16 ***
    ## m_preg_wt_gain   11.5703     0.6883   16.81   <2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 496.3 on 4340 degrees of freedom
    ## Multiple R-squared:  0.06113,    Adjusted R-squared:  0.06092 
    ## F-statistic: 282.6 on 1 and 4340 DF,  p-value: < 2.2e-16

``` r
coef(wt_gain_model)
```

    ##    (Intercept) m_preg_wt_gain 
    ##     2858.91376       11.57031

-   With a p-value of &lt;2e-16, there is sufficient evidence to suggest mother’s weight gain during pregnancy is a significant predictor of a baby's birthweight.

``` r
gest_age_wks_model = lm(b_bwt ~ gest_age_wks, data = birthweight_data)
summary(gest_age_wks_model)
```

    ## 
    ## Call:
    ## lm(formula = b_bwt ~ gest_age_wks, data = birthweight_data)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1730.52  -292.85    -0.78   303.47  1591.36 
    ## 
    ## Coefficients:
    ##              Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)   476.003     88.809    5.36 8.76e-08 ***
    ## gest_age_wks   66.920      2.245   29.80  < 2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 466.7 on 4340 degrees of freedom
    ## Multiple R-squared:  0.1699, Adjusted R-squared:  0.1697 
    ## F-statistic: 888.3 on 1 and 4340 DF,  p-value: < 2.2e-16

``` r
coef(gest_age_wks_model)
```

    ##  (Intercept) gest_age_wks 
    ##    476.00261     66.91991

-   With a p-value of &lt;2e-16, there is sufficient evidence to suggest gestational age is a significant predictor of a baby's birthweight.

``` r
m_age_delivery_model = lm(b_bwt ~ m_age_delivery, data = birthweight_data)
summary(m_age_delivery_model)
```

    ## 
    ## Call:
    ## lm(formula = b_bwt ~ m_age_delivery, data = birthweight_data)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -2514.04  -291.97    20.03   332.03  1717.82 
    ## 
    ## Coefficients:
    ##                Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)    2750.407     41.047  67.007   <2e-16 ***
    ## m_age_delivery   17.932      1.986   9.028   <2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 507.5 on 4340 degrees of freedom
    ## Multiple R-squared:  0.01843,    Adjusted R-squared:  0.01821 
    ## F-statistic: 81.51 on 1 and 4340 DF,  p-value: < 2.2e-16

``` r
coef(m_age_delivery_model)
```

    ##    (Intercept) m_age_delivery 
    ##     2750.40746       17.93159

-   With a p-value of &lt;2e-16, there is sufficient evidence to suggest mother’s age at delivery is a significant predictor of a baby's birthweight.

-   All of the proposed predictors were individually significant, so a multivariable linear model was made using all three.

``` r
my_bw_model = lm(b_bwt ~ m_preg_wt_gain + gest_age_wks + m_age_delivery, data = birthweight_data)
my_bw_model
```

    ## 
    ## Call:
    ## lm(formula = b_bwt ~ m_preg_wt_gain + gest_age_wks + m_age_delivery, 
    ##     data = birthweight_data)
    ## 
    ## Coefficients:
    ##    (Intercept)  m_preg_wt_gain    gest_age_wks  m_age_delivery  
    ##        240.988           9.471          59.988          14.738

``` r
summary(my_bw_model)
```

    ## 
    ## Call:
    ## lm(formula = b_bwt ~ m_preg_wt_gain + gest_age_wks + m_age_delivery, 
    ##     data = birthweight_data)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1772.53  -289.29     6.08   294.96  1545.50 
    ## 
    ## Coefficients:
    ##                Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)    240.9880    90.2803   2.669  0.00763 ** 
    ## m_preg_wt_gain   9.4709     0.6392  14.817  < 2e-16 ***
    ## gest_age_wks    59.9882     2.2234  26.980  < 2e-16 ***
    ## m_age_delivery  14.7382     1.7958   8.207 2.96e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 453.2 on 4338 degrees of freedom
    ## Multiple R-squared:  0.2175, Adjusted R-squared:  0.2169 
    ## F-statistic: 401.9 on 3 and 4338 DF,  p-value: < 2.2e-16

``` r
coef(my_bw_model)
```

    ##    (Intercept) m_preg_wt_gain   gest_age_wks m_age_delivery 
    ##     240.987977       9.470899      59.988212      14.738213

-   The null hypothesis is that this model has no predictive value of a baby's birth weight. The alternative hypothesis is that this model has some predictive value of a baby's birth weight.
-   This multivariable model was found to have an F-statistic of 401.9 on 3 and 4338 Degrees of freedom with a p-value of &lt; 2.2e-16.
-   Based on this F-statistic and p-value, we reject the null hyphothesis and conclude that the mother’s weight gain during pregnancy (in pounds), gestational age (in weeks), and the mother's age during delivery are significant predictors of a baby's birthweight.
-   With an R-squared value of 0.2175, 21.75% of the variation in a baby's birthweight can be explained by this linear model, the rest remains unexplained.

Plot of model residuals against fitted values
---------------------------------------------

``` r
resid_fit_plot = birthweight_data %>% 
  add_predictions(my_bw_model) %>%
  add_residuals(my_bw_model) %>%
  ggplot(aes(x = resid, y = pred)) + geom_point() + 
  geom_smooth(aes(y = pred))

resid_fit_plot
```

    ## `geom_smooth()` using method = 'gam' and formula 'y ~ s(x, bs = "cs")'

![](p8105_hw6_mrc2229_files/figure-markdown_github/unnamed-chunk-6-1.png)

-   The above plot shows my birthwieght predicting linear model's residuals against the fitted values from the model. A smooth predictive line was added to the model.

Comparing my model to two others
--------------------------------
